apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ir-data
  namespace: ir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  # Static NFS PV binding (see pv-ir-nfs.yaml)
  volumeName: ir-data-nfs
  storageClassName: ""

