apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ir-data
  namespace: ir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Set your cluster StorageClass here if needed:
  # storageClassName: standard

