apiVersion: v1
kind: Service
metadata:
  name: ir-gateway
  namespace: ir
spec:
  type: NodePort
  selector:
    app: ir-gateway
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: enroll
      port: 8443
      targetPort: 8443
      nodePort: 30444

