apiVersion: v1
kind: Service
metadata:
  name: ir-orchestrator-ui
  namespace: ir
spec:
  type: NodePort
  selector:
    app: ir-orchestrator
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080

